PlayerCombat
ArthurHSouza/GaelThroughDimensions pull request #4
Opened 2024-03-20 23:22 UTC by brennocurtolo

Essa branch esta mergeada com a movimentacao_e_mundo. Aqui temos algumas implementações para o damage do player e enemy geral.
Acredito que resolvi os conflitos sem deixar erros.
A Scene PlayerCombat tem uma interação de receber dano ao encostar no inimigo e promover dano ao clicar com o mouse0 (Esquerdo).

<video width="320" height="240" controls>
  <source src="https://github.com/ArthurHSouza/GaelThroughDimensions/assets/87980999/3e99e804-d905-47e1-86bb-2a04aa7dc3d2">
</video>

2024-03-26 17:12 UTC, Gabril0 submitted a review, later dismissed
Perdão pela demora, ficou muito bom!! Só acredito que tenhamos que mudar a layer dos pontos de patrulha do inimigo para IgnoreRayCast, se não o jogador fica preso por conta de estar identificando um colisor. Outra coisa que precisamos mudar é a força do gancho para inimigos, mas acredito que seja melhor arrumar esse mais tarde quando tivermos mais parâmetros definidos, por hora é necessário por volta de 200 de força para puxar o inimigo com 1 de massa.
Portanto acho que precisa mudar somente a questão das layers que aí já pode dar merge, vou deixar aprovado mas lembre de fazer essa mudança por favor.

2024-03-26 22:43 UTC, ArthurHSouza commented
Remova a scene que o player tem animação, e remova ou comente o código em que você está atualização ela, no momento está tendo um warning no console o tempo todo.

2024-03-26 22:46 UTC, ArthurHSouza requested changes
Remova a scene que o player tem animação, e remova ou comente o código em que você está atualização ela, no momento está tendo um warning no console o tempo todo.

2024-03-30 14:39 UTC, ArthurHSouza approved these changes

2024-03-30 19:35 UTC, Gabril0 approved these changes

2024-03-30 19:58 UTC, merged